### ISSUE TITLE
问个小问题

### ISSUE THREAD

**Issue by world2025** [flyingpot/center_loss_pytorch#1]
将sofltmax loss和center loss一起用是不是类似于用LDA算法呢

**Comment by world2025** [comment]
还有就是这两个怎么一起用呢

**Comment by spoonnotfound** [comment]
LDA目的是降维，而将softmax loss和center loss结合则是在增大类间距离的同时减小类内距离，思想上可能比较类似吧。
两者的结合你可以自己试验一下，将两个损失函数联合优化，加一个权重就可以了。

**Comment by world2025** [comment]
嗯嗯，好的，谢谢！
